### ISSUE TITLE
Do not force the `editor.gotoLocation.multipleDefinitions": "goto"` in project `.vscode/settings.json`

### ISSUE THREAD

**Issue by madebyfabian** [alimozdemir/vscode-nuxt-dx-tools#3]
Hi there! Thanks for the awesome extension!
I noticed that I already have `editor.gotoLocation.multipleDefinitions": "goto"` set in my system-wide `settings.json` (so basically the global VSCode Settings). But every time I start VSCode, it edits the `.vscode/settings.json` file in any of my projects and adds this line to it.
Is it required to have this line in every project? Or does it also get recognized if it's in the system-wide settings file.

**Comment by alimozdemir** [comment]
Hi @madebyfabian thank you for the feedback. 

I have improved the prompt and config logic of the extension and released in v1.5.0

https://github.com/alimozdemir/vscode-nuxt-dx-tools/tree/v1.5.0?tab=readme-ov-file#configuration

Thanks!

**Comment by madebyfabian** [comment]
Awesome, thank you! Appreciate it.
